/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 book.gltf --transform 
Files: book.gltf [20.14MB] > C:\Users\arjun\Desktop\book_open\book-transformed.glb [860.34KB] (96%)
Author: FlukierJupiter (https://sketchfab.com/FlukierJupiter)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/book-open-bcc69dacd1bc4eadaf4b9fc0d6e2430b
Title: Book Open
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./book-transformed.glb')
  return (
    <group {...props}  scale ={10} dispose={null}>
      <mesh geometry={nodes['BookOpen_LP_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-0.181, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/book-transformed.glb')
