/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 vinyl.gltf --transform 
Files: vinyl.gltf [85.1MB] > C:\Users\arjun\Desktop\vinyl\vinyl-transformed.glb [581.89KB] (99%)
Author: plaggy (https://sketchfab.com/plaggy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cc0-10-inch-vinyl-record-sgt-holmes-b0d0d7511e91453a8b3bd7f142abfa6e
Title: CC0 - 10 inch Vinyl Record Sgt Holmes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./vinyl-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.VinylRecordSgtHolmes_VinylRecordSgtHolmes_0.geometry} material={materials.VinylRecordSgtHolmes} position={[0.081, -0.007, 0.016]} rotation={[-0.29, -0.168, -0.132]} scale={0.025} />
      <mesh geometry={nodes.VinylRecordSgtHolmesSleeve_VinylRecordSgtHolmesSleeve_0.geometry} material={materials.VinylRecordSgtHolmesSleeve} position={[-0.082, 0.007, -0.016]} rotation={[-1.838, 0.131, -0.169]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('/vinyl-transformed.glb')
